# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20170727_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.CharField(max_length=1400),
        ),
    ]
