# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20170731_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='department',
            field=models.CharField(default='toDetermine', max_length=100),
            preserve_default=False,
        ),
    ]
