# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_component_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='common_unit',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Component'),
        ),
    ]
