# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20170805_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.CharField(max_length=5000),
        ),
    ]
